apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jackett
  namespace: media
spec:
  storageClassName: "jackett"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
