apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbit
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - qbit.defconsandbox.com
    secretName: qbit-media
  rules:
  - host: qbit.defconsandbox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: qbittorrent-service
            port:
              number: 80
