apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qbit
  namespace: media
spec:
  storageClassName: "qbit"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume2/k8s/pv/qbit
    server: 10.1.20.2
