apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbit
  namespace: media
spec:
  storageClassName: "qbit"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
