apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sab
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - sab.defconsandbox.com
    secretName: sab-media
  rules:
  - host: sab.defconsandbox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: sabnzbd-service
            port:
              number: 8080
