apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sab
  namespace: media
spec:
  storageClassName: "sab"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
