apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: my.email@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector:
        dnsZones:
          - "defconsandbox.com"
      dns01:
        route53:
          region: us-east-1
          accessKeyID: 'AKIAXAEO7AWFRWOQ4LMU'
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
